### ISSUE TITLE
Policy Scanner is broken for AppEngine Flex

### ISSUE THREAD

**Issue by carise** [GoogleCloudPlatform/policyscanner#33]
Similar to https://github.com/xerial/snappy-java/issues/146

**Comment by srineels** [comment]
I'm having the same issue running the policy scanner on my local

Problem accessing /check_states. Reason:
    [FAILED_TO_LOAD_NATIVE_LIBRARY] access denied ("java.io.FilePermission" "/var/folders/54/358vhns15pg5mddylz9qw5zrmhcn3f/T" "read")
Caused by:
org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] access denied ("java.io.FilePermission" "/var/folders/54/358vhns15pg5mddylz9qw5zrmhcn3f/T" "read")
	at org.xerial.snappy.SnappyLoader.load(SnappyLoader.java:159) ...


On App Engine - I'm getting this error:
org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] null
at org.xerial.snappy.SnappyLoader.load (SnappyLoader.java:159)
at org.xerial.snappy.Snappy.<clinit> (Snappy.java:47)

**Comment by carise** [comment]
@srineels Thanks for the report! Working on it.
